version: '3'

services:
  lab-postgres-dac:
    image: postgres
    environment:
      POSTGRES_USER: "dac"
      POSTGRES_PASSWORD: "dac"
    ports:
      - "5432:5432"
    volumes:
      - practical_sql:/var/lib/postgresql/data
    networks:
      - postgres-compose-network
    restart: on-failure

networks:
  postgres-compose-network:
    driver: bridge

volumes:
  practical_sql:
